on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: mkdir ~/.ssh && echo $PRIVATE_KEY > ~/.ssh/id_rsa
      - run: npm i
      - run: npm run build
      - run: tar cf site.tar.gz -C _site/ .
      - run: ssh maarika@maarika.space 'rm -rf /var/www/retseptid/*'
      - run: scp site.tar.gz maarika@maarika.space:/var/www/retseptid
      - run: ssh maarika@maarika.space 'cd /var/www/retseptid && tar xf site.tar.gz && rm site.tar.gz'
